// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/voice-chat.proto

package voicechat

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type VoiceSample struct {
	// speaker is the current speaker of the sound
	Speaker string `protobuf:"bytes,1,opt,name=speaker,proto3" json:"speaker,omitempty"`
	// sample is going to be flac encoded sample of sound.
	Sample               []byte   `protobuf:"bytes,2,opt,name=sample,proto3" json:"sample,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoiceSample) Reset()         { *m = VoiceSample{} }
func (m *VoiceSample) String() string { return proto.CompactTextString(m) }
func (*VoiceSample) ProtoMessage()    {}
func (*VoiceSample) Descriptor() ([]byte, []int) {
	return fileDescriptor_69b82e3f659f75e9, []int{0}
}
func (m *VoiceSample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoiceSample.Unmarshal(m, b)
}
func (m *VoiceSample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoiceSample.Marshal(b, m, deterministic)
}
func (m *VoiceSample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoiceSample.Merge(m, src)
}
func (m *VoiceSample) XXX_Size() int {
	return xxx_messageInfo_VoiceSample.Size(m)
}
func (m *VoiceSample) XXX_DiscardUnknown() {
	xxx_messageInfo_VoiceSample.DiscardUnknown(m)
}

var xxx_messageInfo_VoiceSample proto.InternalMessageInfo

func (m *VoiceSample) GetSpeaker() string {
	if m != nil {
		return m.Speaker
	}
	return ""
}

func (m *VoiceSample) GetSample() []byte {
	if m != nil {
		return m.Sample
	}
	return nil
}

func init() {
	proto.RegisterType((*VoiceSample)(nil), "voicechat.VoiceSample")
}

func init() { proto.RegisterFile("pb/voice-chat.proto", fileDescriptor_69b82e3f659f75e9) }

var fileDescriptor_69b82e3f659f75e9 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x48, 0xd2, 0x2f,
	0xcb, 0xcf, 0x4c, 0x4e, 0xd5, 0x4d, 0xce, 0x48, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x04, 0x8b, 0x80, 0x04, 0x94, 0xec, 0xb9, 0xb8, 0xc3, 0x40, 0x9c, 0xe0, 0xc4, 0xdc, 0x82,
	0x9c, 0x54, 0x21, 0x09, 0x2e, 0xf6, 0xe2, 0x82, 0xd4, 0xc4, 0xec, 0xd4, 0x22, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48, 0x8c, 0x8b, 0xad, 0x18, 0xac, 0x46, 0x82, 0x49, 0x81,
	0x51, 0x83, 0x27, 0x08, 0xca, 0x4b, 0x62, 0x03, 0x1b, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x96, 0x39, 0x69, 0xf5, 0x69, 0x00, 0x00, 0x00,
}
